# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_직각삼각형출력하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 직각삼각형 출력하기

n = int(input())

for i in range(n):
    print("*"*(i+1))