# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_2차원으로만들기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 2차원으로 만들기
def solution(num_list, n):
    row = []
    answer = []
    for i in num_list:
        row.append(i)
        if len(row) == n:
            answer.append(row)
            row = []
    return answer