# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_배열회전시키기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 배열 회전시키기

def solution(number, direction):
    if direction == 'right':
        num = number[len(number)-1]
        print(num)
        number.pop()
        print(number)
        number.insert(0, num)
        return number
    else:
        num = number[0]
        number.pop(0)
        number.append(num)
        return number

