# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_가까운수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 가까운 수
def solution(array, n):
    num_c = float('inf')
    index_answer = 0
    array_sorted = sorted(array)
    for i in range(len(array_sorted)):
        num_diff = abs(n - array_sorted[i])
        if num_c > num_diff:
            num_c = num_diff
            index_answer = i
        elif num_diff == 0:
            index_answer = i
            break
    return array_sorted[index_answer]