# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_중복된문자제거.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 중복된 문자 제거 

def solution(my_string):
    answer = '' 
    for i in my_string:
        if i in set(my_string) and i not in answer:
            answer += i
    return answer