# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_약수구하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 약수 구하기

def solution(n):
    return [i for i in range(1, n+1) if n % i == 0]