# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_문자열정렬하기(1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 문자열 정렬하기 (1)
def solution(my_string):
    list_str = list(filter(lambda x: x.isdigit(), list(my_string)))
    return sorted(list(map(lambda x: int(x), list_str)))