# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_팩토리얼.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 팩토리얼
def solution(n):
    answer = 1
    for i in range(1, 11):
        answer *= i
        if answer > n:
            return i - 1
        elif answer == n:
            return i