# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_숨어있는숫자의덧셈(2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 숨어있는 숫자의 덧셈 (2)
import re
def solution(my_string):
    return sum([int(i) for i in re.findall(r'(\d+)', my_string)])