# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_진료순서정하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 진료순서 정하기

def solution(emergency):
    emergency_sorted = sorted(emergency, reverse=True)
    answer = []
    for i in emergency:
        answer.append(emergency_sorted.index(i) + 1)
    return answer