# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_숫자찾기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 숫자찾기
def solution(num, k):
    if str(num).find(str(k)) >= 0:
        return str(num).index(str(k))+1
    else:
        return -1