# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_A로B만들기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# A로 B 만들기
def solution(before, after):
    if sorted(before) == sorted(after):
        return 1
    return 0