# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_가장큰수찾기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 가장 큰 수 찾기

def solution(array):
    return [max(array), array.index(max(array))]