# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_n의배수고르기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# n의 배수 고르기

def solution(n, numlist):
    return list(filter(lambda x: x % n == 0, numlist))