# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_암호해독.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 암호 해독
def solution(cipher, code):
    count = 0
    answer = ""
    for i in cipher:
        count += 1
        if count % code == 0:
            answer += i
    return answer



