# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_외계행성의나이.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 외계행성의 나이

def solution(age):
    alpha_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
    answer =''
    for i in str(age):
        answer += alpha_list[int(i)]
    return answer

