# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_369게임.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 369게임

def solution(order):
    return str(order).count('3') + str(order).count('6') + str(order).count('9')