# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_한 번만 등장한 문자.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 한 번만 등장한 문자
def solution(s):
    return ''.join(sorted([i for i in set(s) if s.count(i) == 1]))