# -*- coding: utf-8 -*-
"""Lv0_프로그래머스_최댓값만들기(2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7V6PjgqE7MsMXFyyQRIx6jJ23iFZR4w
"""

# 최댓값 만들기(2)

def solution(numbers):
    a = sorted(numbers)
    b = sorted(numbers, reverse = True)
    if a[0]*a[1] > b[0]*b[1]:
        return a[0]*a[1]
    return b[0]*b[1]